import { Inter } from 'next/font/google'

import type { Metadata } from 'next'

import Navbar from '@/components/navbar/navbar'
import Scene from '@/components/canvas/Scene'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-[minmax(42rem,_1fr)_30rem] h-screen bg-slate-900">
          <section className="h-screen">
            <Scene />
          </section>
          <section className="flex h-screen bg-slate-900">
            <Navbar />
            {children}
          </section>
        </div>
      </body>
    </html>
  )
}
